### ISSUE TITLE
Python 3 version?

### ISSUE THREAD

**Issue by rmbw51** [lisette-espin/mrqap#1]
Nice package, I have used it in the past. Now I had to go to Python 3 and it doesn't work anymore,
any idea to upgrade? it's practically the only MRQAP Python package existing.
Many thanks

**Comment by lisette-espin** [comment]
Hi, thanks for using it.
I can try to work on the Python 3 version.
Will keep you posted.

**Comment by rmbw51** [comment]
thanks

**Comment by lisette-espin** [comment]
I have created a new branch **[p3](https://github.com/lisette-espin/mrqap-python/tree/p3)** with the code for Python 3.
Check it out.

**Comment by rmbw51** [comment]
many thanks
